"""add principals and skill permissions

Revision ID: 9b1420cf715c
Revises: 5388d32d6a7e
Create Date: 2026-09-14 21:04:18.372791

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b1420cf715c"
down_revision: str | Sequence[str] | None = "5388d32d6a7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "principals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_key", sa.String(length=512), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_principals_external_key"), "principals", ["external_key"], unique=True)
    op.create_table(
        "skill_permissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("principal_id", sa.String(length=36), nullable=False),
        sa.Column("permission", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["principal_id"], ["principals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "principal_id", "permission", name="uq_skill_permission"),
    )
    op.create_index(
        op.f("ix_skill_permissions_principal_id"),
        "skill_permissions",
        ["principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_permissions_skill_id"), "skill_permissions", ["skill_id"], unique=False
    )
    op.add_column("audit_events", sa.Column("principal_id", sa.String(length=36), nullable=True))
    op.create_index(
        op.f("ix_audit_events_principal_id"), "audit_events", ["principal_id"], unique=False
    )
    op.create_foreign_key(
        "fk_audit_events_principal_id",
        "audit_events",
        "principals",
        ["principal_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "browser_actions", sa.Column("actor_principal_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_browser_actions_actor_principal_id"),
        "browser_actions",
        ["actor_principal_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_browser_actions_actor_principal_id",
        "browser_actions",
        "principals",
        ["actor_principal_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "recordings", sa.Column("owner_principal_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_recordings_owner_principal_id"), "recordings", ["owner_principal_id"], unique=False
    )
    op.create_foreign_key(
        "fk_recordings_owner_principal_id",
        "recordings",
        "principals",
        ["owner_principal_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "runs", sa.Column("requested_by_principal_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_runs_requested_by_principal_id"),
        "runs",
        ["requested_by_principal_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_runs_requested_by_principal_id",
        "runs",
        "principals",
        ["requested_by_principal_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("skills", sa.Column("owner_principal_id", sa.String(length=36), nullable=True))
    op.create_index(
        op.f("ix_skills_owner_principal_id"), "skills", ["owner_principal_id"], unique=False
    )
    op.create_foreign_key(
        "fk_skills_owner_principal_id",
        "skills",
        "principals",
        ["owner_principal_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_skills_owner_principal_id", "skills", type_="foreignkey")
    op.drop_index(op.f("ix_skills_owner_principal_id"), table_name="skills")
    op.drop_column("skills", "owner_principal_id")
    op.drop_constraint("fk_runs_requested_by_principal_id", "runs", type_="foreignkey")
    op.drop_index(op.f("ix_runs_requested_by_principal_id"), table_name="runs")
    op.drop_column("runs", "requested_by_principal_id")
    op.drop_constraint("fk_recordings_owner_principal_id", "recordings", type_="foreignkey")
    op.drop_index(op.f("ix_recordings_owner_principal_id"), table_name="recordings")
    op.drop_column("recordings", "owner_principal_id")
    op.drop_constraint(
        "fk_browser_actions_actor_principal_id",
        "browser_actions",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_browser_actions_actor_principal_id"), table_name="browser_actions")
    op.drop_column("browser_actions", "actor_principal_id")
    op.drop_constraint("fk_audit_events_principal_id", "audit_events", type_="foreignkey")
    op.drop_index(op.f("ix_audit_events_principal_id"), table_name="audit_events")
    op.drop_column("audit_events", "principal_id")
    op.drop_index(op.f("ix_skill_permissions_skill_id"), table_name="skill_permissions")
    op.drop_index(op.f("ix_skill_permissions_principal_id"), table_name="skill_permissions")
    op.drop_table("skill_permissions")
    op.drop_index(op.f("ix_principals_external_key"), table_name="principals")
    op.drop_table("principals")
    # ### end Alembic commands ###
