"""add approval gates

Revision ID: a6f585d77dc1
Revises: 9b1420cf715c
Create Date: 2026-09-14 21:11:21.904464

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6f585d77dc1"
down_revision: str | Sequence[str] | None = "9b1420cf715c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_version_id", sa.String(length=36), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("gate_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("requested_by_principal_id", sa.String(length=36), nullable=True),
        sa.Column("decided_by_principal_id", sa.String(length=36), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["decided_by_principal_id"],
            ["principals.id"],
            name="fk_approvals_decided_by_principal_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_principal_id"],
            ["principals.id"],
            name="fk_approvals_requested_by_principal_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"], ["workflow_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "workflow_version_id",
            "step_index",
            "gate_fingerprint",
            name="uq_approval_gate_instance",
        ),
    )
    op.create_index(
        op.f("ix_approvals_decided_by_principal_id"),
        "approvals",
        ["decided_by_principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approvals_requested_by_principal_id"),
        "approvals",
        ["requested_by_principal_id"],
        unique=False,
    )
    op.create_index(op.f("ix_approvals_run_id"), "approvals", ["run_id"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_index(
        op.f("ix_approvals_workflow_version_id"), "approvals", ["workflow_version_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_workflow_version_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_run_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_requested_by_principal_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_decided_by_principal_id"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
